dist: xenial

matrix: 
  include: 
    - language: node_js
      node_js: node
      script:
      - cd frontend
      - npm audit
      - npm install
      - npm run lint
    - language: python
      python: 3.6
      install: "pip install tox"
      script: "cd api && tox"
  allow_failures:
    - language: python
      python: 3.6
