dist: xenial

matrix: 
  include: 
    - language: node_js
      node_js: node
      script:
      - cd frontend
      - npm audit
      - npm install
      - npm run lint
    - language: python
      python: 3.6
      install:
        - cd api
        - pip install -r requirements.txt
        - pip install -r test-requirements.txt
      script:
        - cd api
        - nosetests
        - flake8 --ignore=E501 openapi_server
