openapi: 3.0.0
info:
  description: Short-read sequencing tools
  version: "2018_11"
  title: GSVarWeb
  contact:
    email: marc.sturm@med.uni-tuebingen.de
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
tags:
  - name: rating
    description: Tools to handle rating of individual files (annotation)
  - name: ngs-bits
    description: Various tools depending on ngs-bits
  - name: megSAP
    description: Various tools depending on megSAP
  - name: files
    description: Controller dealing with file related issues
paths:
  /upload:
    post:
      description: Uploads a file to the server
      tags: 
        - files
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                uploadedFile:
                  description: The GSVar file to upload.
                  type: string
                  format: binary
      responses:
        "200":
          description: successfull
        "400":
          description: failed, e.g file can not be uploaded
          content:
            "*/*":
              schema:
                type: string
  "/vcf2gsvar/{filePath}":
    get:
      description: "Converts a VCF file to a GSvar"
      tags:
        - megSAP
      parameters: 
        - name: filePath
          in: path
          description: The GSvar file to convert
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successfull
          content:
            application/json:
              schema:
                type: number
        "400":
          description: error
          content:
            application/json:
              schema:
                type: string
  "/an_vep/{filePath}":
    get:
      description: "Annotates a VCF using VEP"
      tags:
        - megSAP
      parameters: 
        - name: filePath
          in: path
          description: The VCF file to annotate
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successfull
          content:
            application/json:
              schema:
                type: number
        "400":
          description: error
          content:
            application/json:
              schema:
                type: string
  "/count/{filePath}":
    get:
      description: Count items in a file
      tags:
        - files
      parameters:
        - name: filePath
          in: path
          description: Path to the file
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successfull
          content:
            application/json:
              schema:
                type: number
  "/download/{filePath}":
    get:
      description: Download a file from given path eventually cutting it with Lines header
      tags: 
        - files
      parameters:
        - name: filePath
          in: path
          description: Path to the file
          required: true
          schema:
            type: string
        - name: Lines
          in: header
          description: The lines to serve represented as from-to e.g 1-100 starting at 1
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successfull
          content:
            text/gsvar:
              schema:
                type: string
                format: binary
  "/VcfCheck/{filePath}":
    get:
      description: Check a file at given path with VcfCheck.
      tags:
        - ngs-bits
      parameters:
        - name: filePath
          in: path
          description: Path to file
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successfull
        "400":
          description: error
          content:
            application/json:
              schema:
                type: string
  /VariantFilterAnnotations:
    post:
      tags:
        - ngs-bits
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VariantFilterRequest"
      responses:
        "200":
          description: successfull
        "400":
          description: bad request
          content:
            application/json:
              schema:
                type: string
  "/rate/":
    put:
      description: Rate a file. This uses JWT to verify the user.
      tags:
        - rating
      parameters:
        - name: filePath
          in: query
          description: Path to file
          required: true
          schema:
            type: string
        - name: chr
          in: query
          description: The chromosome to rate for
          required: true
          schema:
            type: string
        - name: start
          in: query
          description: The start position to rate for
          required: true
          schema:
            type: number
        - name: end
          in: query
          description: The end position to annotate for
          required: true
          schema:
            type: number
        - name: rating
          in: query
          description: Which rating this variant should have.
          required: true
          schema:
            type: number
            maximum: 5
            minimum: 1
      responses:
        "200":
          description: successfull
        "400":
          description: error
          content:
            application/json:
              schema:
                type: string
  "/annotated/{filePath}":
    get:
      description: Retrieves an annotated version of the file.
      tags:
        - rating
      parameters:
        - name: filePath
          in: path
          description: Path to file
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successfull
        "400":
          description: error
          content:
            application/json:
              schema:
                type: string
      
externalDocs:
  description: Find out more about GSVarWeb
  url: https://github.com/imgag/GSvarWeb
servers:
  - url: /v1
components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    VariantFilterRequest:
      type: object
      properties:
        in:
          type: string
          format: file
        out:
          type: string
          format: file
        filter:
          type: array
          items:
            type: object
          description: The filter dict to apply
security: 
  - jwt: ['secret']

