---
swagger: "2.0"
info:
  description: "Short-read sequencing tools"
  version: "2018_11"
  title: "ngs-bits"
  contact:
    email: "marc.sturm@med.uni-tuebingen.de"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
basePath: "/v1"
tags:
- name: "VariantFilterAnnotations"
  description: "Filters variants by annotation"
schemes:
- "http"
- "https"
paths:
  /download/{filePath}:
    get:
      operationId: "download_file_path_get"
      produces:
      - "text/gsvar"
      parameters:
      - name: "filePath"
        in: "path"
        description: "Path to the file"
        required: true
        type: "string"
      responses:
        200:
          description: "successful"
          schema:
            type: "file"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /VariantFilterAnnotations:
    post:
      tags:
      - "VariantFilterAnnotations"
      operationId: "variant_filter_annotations_post"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/VariantFilterRequest"
      responses:
        200:
          description: "successful"
        400:
          description: "bad request"
          schema:
            type: "string"
      x-swagger-router-controller: "swagger_server.controllers.variant_filter_annotations_controller"
definitions:
  VariantFilterRequest:
    type: "object"
    properties:
      in:
        type: "string"
        format: "file"
      out:
        type: "string"
        format: "file"
      filter:
        type: "array"
        description: "The filter dict to apply"
        items:
          type: "object"
          properties: {}
externalDocs:
  description: "Find out more about ngs-bits"
  url: "http://github.com/imgag/ngs-bits"
